### ISSUE TITLE
telegram integration

### ISSUE THREAD

**Issue by geeks121** [alessio-ds/bsc-whales-monitor#2]
how to integrate the log to telegram bot?
btw thanks for making this project available open source

**Comment by alessio-ds** [comment]
first of all, thanks for appreciating it! ❤️🙏👑

the easiest way to integrate this program to a telegram bot would be to send the variable `dstg` as a message, as it contains everything (tx url, emojis and quantity)

the lines where you should add the telegram send msg function are [203](https://github.com/alessio-ds/BSCWhalesMonitor/blob/628841485baccfcdee12357ef003308dccf1fc81/BSCWhales.py#L203) and [314](https://github.com/alessio-ds/BSCWhalesMonitor/blob/628841485baccfcdee12357ef003308dccf1fc81/BSCWhales.py#L314)

if you do, please mention me! 🤣
