### ISSUE TITLE
Free bscscan API limits 5 transaction per second

### ISSUE THREAD

**Issue by Ocean47** [alessio-ds/bsc-whales-monitor#9]
I am not sure if the app is working as i am using the free api from bscscan, as the lowest plan is like $200USD a month which is far more than I am willing to pay to monitor whales. But it runs, just stops constantly, and keepins saying Blocks to Check:  with an slowly increasing number. Which means I don't know if it is actually working, or gets paused and reset before it can actually do any searching of the transactions.  I will have to dig into the script to see what might be going on.  But if anyone has encountered this and knows if the app will still work like this, or if there is an easy fix/change to the code that will work, be very interested to know.  Might save me a lot of effort...

**Comment by alessio-ds** [comment]
As you can see here, the program should be sending up to 3 requests/second:
https://github.com/alessio-ds/BSCWhalesMonitor/blob/a74cde434b26930d4db6f4cc3f3dba00d1e9c6a4/BSCWhales.py#L212

Please refer to line 211 if you want to change the timer (higher=more delay=less requests per second)
https://github.com/alessio-ds/BSCWhalesMonitor/blob/a74cde434b26930d4db6f4cc3f3dba00d1e9c6a4/BSCWhales.py#L211
